version: '3.8'

services:
  # 1. Le Broker Réseau Volatile (Sans volume persistant pour la v1_limit)
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  # 2. Brique IA
  ia-analyzer:
    build: .
    ports:
      - "8000:8000"
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672/%2F
    depends_on:
      - rabbitmq

  # 3. Le générateur d'antenne télécom
  generator:
    build: .
    command: python generator.py
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672/%2F
    depends_on:
      - rabbitmq

  # 4. Le conteneur éphémère de test
  tester:
    build: .
    command: python test_observability.py
    network_mode: "host"
    depends_on:
      - ia-analyzer
      - generator     
